spring:
  profiles:
    active: development
---
spring:
  profiles: development
#redis:
# host: 192.168.99.100
# port: 6379
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672    	
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#graphite.host: 192.168.99.100
#graphite.port: 2003
---
spring:
  profiles: docker
#  redis:
#    host: redis
#    port: 6379
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: cloud
#  redis:
#    host: ${vcap.services.catalog-redis.credentials.hostname:localhost}
#    port: ${vcap.services.catalog-redis.credentials.port:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysqldb?useSSL=false
    username: admin
    password: admin
    initialize: true
# rabbitmq:
#   host: 192.168.99.100
#   port: 5672    	
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_SERVICE_HOST}:${DISCOVERY_SERVICE_SERVICE_PORT}/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false